In [1]:
import pandas as pd
import numpy as np

print("Pandas:", pd.__version__)
print("NumPy:", np.__version__)

Pandas: 3.0.6
NumPy: 2.5.3

In [9]:
import pandas as pd

df = pd.read_csv("../data/online_retail_II.csv")

df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../data/online_retail_II.csv'

In [10]:
import os

print(os.listdir("../"))
print(os.listdir("../data"))

['data', 'notebook', 'report', 'screenshots']
['.ipynb_checkpoints', 'online_retail_II.csv.zip']

In [11]:
df = pd.read_csv("../data/online_retail_II.csv")

df.head()

FileNotFoundError: [Errno 2] No such file or directory: '../data/online_retail_II.csv'

In [12]:
df = pd.read_csv("../data/online_retail_II.csv.zip", compression="zip")
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
0,489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom
1,489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
2,489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom
3,489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom
4,489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom

In [13]:
print("Rows and columns:", df.shape)

print("\nColumn names:")
print(df.columns.tolist())

print("\nData types:")
print(df.dtypes)

Rows and columns: (1067371, 8)

Column names:
['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country']

Data types:
Invoice            str
StockCode          str
Description        str
Quantity         int64
InvoiceDate        str
Price          float64
Customer ID    float64
Country            str
dtype: object

In [14]:
df.isnull().sum()

Invoice             0
StockCode           0
Description      4382
Quantity            0
InvoiceDate         0
Price               0
Customer ID    243007
Country             0
dtype: int64

In [15]:
missing = df.isnull().sum()
missing_percent = (missing / len(df)) * 100

pd.DataFrame({
    "Missing Values": missing,
    "Missing Percentage": missing_percent.round(2)
})

             Missing Values  Missing Percentage
Invoice                   0                0.00
StockCode                 0                0.00
Description            4382                0.41
Quantity                  0                0.00
InvoiceDate               0                0.00
Price                     0                0.00
Customer ID          243007               22.77
Country                   0                0.00

In [16]:
df.duplicated().sum()

np.int64(34335)

In [17]:
df[["Quantity", "Price"]].describe()

           Quantity         Price
count  1.067371e+06  1.067371e+06
mean   9.938898e+00  4.649388e+00
std    1.727058e+02  1.235531e+02
min   -8.099500e+04 -5.359436e+04
25%    1.000000e+00  1.250000e+00
50%    3.000000e+00  2.100000e+00
75%    1.000000e+01  4.150000e+00
max    8.099500e+04  3.897000e+04

In [18]:
print("Negative Quantity:", (df["Quantity"] < 0).sum())
print("Negative Price:", (df["Price"] < 0).sum())

print("\nZero Quantity:", (df["Quantity"] == 0).sum())
print("Zero Price:", (df["Price"] == 0).sum())

Negative Quantity: 22950
Negative Price: 5

Zero Quantity: 0
Zero Price: 6202

In [19]:
df[df["Quantity"] < 0][["Invoice", "StockCode", "Description", "Quantity", "Price"]].head(10)

     Invoice StockCode                        Description  Quantity  Price
178  C489449     22087           PAPER BUNTING WHITE LACE       -12   2.95
179  C489449    85206A       CREAM FELT EASTER EGG BASKET        -6   1.65
180  C489449     21895      POTTING SHED SOW 'N' GROW SET        -4   4.25
181  C489449     21896                 POTTING SHED TWINE        -6   2.10
182  C489449     22083         PAPER CHAIN KIT RETRO SPOT       -12   2.95
183  C489449     21871                SAVE THE PLANET MUG       -12   1.25
184  C489449     84946    ANTIQUE SILVER TEA GLASS ETCHED       -12   1.25
185  C489449    84970S  HANGING HEART ZINC T-LIGHT HOLDER       -24   0.85
186  C489449     22090          PAPER BUNTING RETRO SPOTS       -12   2.95
196  C489459    90200A         PURPLE SWEETHEART BRACELET        -3   4.25

In [20]:
df[df["Price"] < 0][
    ["Invoice", "StockCode", "Description", "Quantity", "Price"]
]

        Invoice StockCode      Description  Quantity     Price
179403  A506401         B  Adjust bad debt         1 -53594.36
276274  A516228         B  Adjust bad debt         1 -44031.79
403472  A528059         B  Adjust bad debt         1 -38925.87
825444  A563186         B  Adjust bad debt         1 -11062.06
825445  A563187         B  Adjust bad debt         1 -11062.06

In [21]:
df[df["Price"] == 0][
    ["Invoice", "StockCode", "Description", "Quantity", "Price"]
].head(20)

     Invoice StockCode          Description  Quantity  Price
263   489464     21733         85123a mixed       -96    0.0
283   489463     71477                short      -240    0.0
284   489467    85123A          21733 mixed      -192    0.0
470   489521     21646                  NaN       -50    0.0
3114  489655     20683                  NaN       -44    0.0
3161  489659     21350                  NaN       230    0.0
3162  489660     35956                 lost     -1043    0.0
3168  489663    35605A              damages      -117    0.0
3731  489781     84292                  NaN        17    0.0
4296  489806     18010                  NaN      -770    0.0
4538  489820     21133      invcd as 84879?      -720    0.0
4566  489821    85049G                  NaN      -240    0.0
4674  489825     22076   6 RIBBONS EMPIRE          12    0.0
5904  489861       DOT       DOTCOM POSTAGE         1    0.0
6378  489882    35751C                  NaN        12    0.0
6555  489898    79323G                  NaN       954    0.0
6556  489899   79323GR         sold as gold      -954    0.0
6576  489901     21098                  NaN      -200    0.0
6581  489903     21166                  NaN        48    0.0
6781  489998     48185  DOOR MAT FAIRY CAKE         2    0.0

In [22]:
df["InvoiceDate"].head(10)

0    2009-12-01 07:45:00
1    2009-12-01 07:45:00
2    2009-12-01 07:45:00
3    2009-12-01 07:45:00
4    2009-12-01 07:45:00
5    2009-12-01 07:45:00
6    2009-12-01 07:45:00
7    2009-12-01 07:45:00
8    2009-12-01 07:46:00
9    2009-12-01 07:46:00
Name: InvoiceDate, dtype: str

In [23]:
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

print(df["InvoiceDate"].dtype)

datetime64[us]

In [24]:
print("Missing dates:", df["InvoiceDate"].isnull().sum())
print("Earliest date:", df["InvoiceDate"].min())
print("Latest date:", df["InvoiceDate"].max())

Missing dates: 0
Earliest date: 2009-12-01 07:45:00
Latest date: 2011-12-09 12:50:00

In [25]:
print("Number of countries:", df["Country"].nunique())
print("\nCountries:")
print(df["Country"].unique())

Number of countries: 43

Countries:
<StringArray>
[      'United Kingdom',               'France',                  'USA',
              'Belgium',            'Australia',                 'EIRE',
              'Germany',             'Portugal',                'Japan',
              'Denmark',              'Nigeria',          'Netherlands',
               'Poland',                'Spain',      'Channel Islands',
                'Italy',               'Cyprus',               'Greece',
               'Norway',              'Austria',               'Sweden',
 'United Arab Emirates',              'Finland',          'Switzerland',
          'Unspecified',                'Malta',              'Bahrain',
                  'RSA',              'Bermuda',            'Hong Kong',
            'Singapore',             'Thailand',               'Israel',
            'Lithuania',          'West Indies',              'Lebanon',
                'Korea',               'Brazil',               'Canada',
              'Iceland',         'Saudi Arabia',       'Czech Republic',
   'European Community']
Length: 43, dtype: str

In [26]:
print("Unique descriptions:", df["Description"].nunique())

print("\nSample descriptions:")
print(df["Description"].dropna().unique()[:30])

Unique descriptions: 5698

Sample descriptions:
<StringArray>
['15CM CHRISTMAS GLASS BALL 20 LIGHTS',                  'PINK CHERRY LIGHTS',
                ' WHITE CHERRY LIGHTS',        'RECORD FRAME 7" SINGLE SIZE ',
      'STRAWBERRY CERAMIC TRINKET BOX',          'PINK DOUGHNUT TRINKET POT ',
                 'SAVE THE PLANET MUG',  'FANCY FONT HOME SWEET HOME DOORMAT',
                           'CAT BOWL ',      'DOG BOWL , CHASING BALL DESIGN',
        'HEART MEASURING SPOONS LARGE',  'LUNCHBOX WITH CUTLERY FAIRY CAKES ',
               'DOOR MAT BLACK FLOCK ',            'LOVE BUILDING BLOCK WORD',
            'HOME BUILDING BLOCK WORD',       'ASSORTED COLOUR BIRD ORNAMENT',
         ' PEACE WOODEN BLOCK LETTERS',        'CHRISTMAS CRAFT WHITE FAIRY ',
           'HEART IVORY TRELLIS LARGE',           'HEART FILIGREE DOVE LARGE',
        'FULL ENGLISH BREAKFAST PLATE',                  'PIZZA PLATE IN BOX',
              'BLACK DINER WALL CLOCK',         'SET OF 3 BLACK FLYING DUCKS',
           'AREA PATROLLED METAL SIGN',       'PLEASE ONE PERSON  METAL SIGN',
            'BATH BUILDING BLOCK WORD',                 'CLASSIC WHITE FRAME',
        'SMALL MARSHMALLOWS PINK BOWL',      'BISCUITS SMALL BOWL LIGHT BLUE']
Length: 30, dtype: str

In [27]:
print("Unique StockCodes:", df["StockCode"].nunique())

print("\nSample StockCodes:")
print(df["StockCode"].unique()[:30])

Unique StockCodes: 5305

Sample StockCodes:
<StringArray>
[ '85048', '79323P', '79323W',  '22041',  '21232',  '22064',  '21871',
  '21523',  '22350',  '22349',  '22195',  '22353', '48173C',  '21755',
  '21754',  '84879',  '22119',  '22142',  '22296',  '22295',  '22109',
  '22107',  '22194', '35004B',  '82582',  '21181',  '21756',  '21333',
 '84596F', '84596L']
Length: 30, dtype: str

In [28]:
duplicates = df.duplicated(
    subset=["Invoice", "StockCode"],
    keep=False
)

print("Rows with duplicate Invoice + StockCode:", duplicates.sum())

Rows with duplicate Invoice + StockCode: 88585

In [29]:
df_clean_test = df.drop_duplicates()

print("Original rows:", len(df))
print("Rows after removing exact duplicates:", len(df_clean_test))
print("Rows removed:", len(df) - len(df_clean_test))

Original rows: 1067371
Rows after removing exact duplicates: 1033036
Rows removed: 34335

In [30]:
df = df.drop_duplicates()

print("Rows after removing duplicates:", len(df))

Rows after removing duplicates: 1033036

In [31]:
df["Description"] = df["Description"].fillna("Unknown")

print("Missing Description:", df["Description"].isnull().sum())

Missing Description: 0

In [32]:
df["Description"] = df["Description"].str.strip()

print(df["Description"].head(10))

0    15CM CHRISTMAS GLASS BALL 20 LIGHTS
1                     PINK CHERRY LIGHTS
2                    WHITE CHERRY LIGHTS
3            RECORD FRAME 7" SINGLE SIZE
4         STRAWBERRY CERAMIC TRINKET BOX
5              PINK DOUGHNUT TRINKET POT
6                    SAVE THE PLANET MUG
7     FANCY FONT HOME SWEET HOME DOORMAT
8                               CAT BOWL
9         DOG BOWL , CHASING BALL DESIGN
Name: Description, dtype: str

In [33]:
df["Customer ID"] = df["Customer ID"].fillna("Unknown")

print("Missing Customer ID:", df["Customer ID"].isnull().sum())

Missing Customer ID: 0

In [34]:
print(df.dtypes)

Invoice                   str
StockCode                 str
Description               str
Quantity                int64
InvoiceDate    datetime64[us]
Price                 float64
Customer ID            object
Country                   str
dtype: object

In [35]:
before = len(df)

df = df[df["Price"] >= 0].copy()

print("Rows removed:", before - len(df))
print("Negative prices remaining:", (df["Price"] < 0).sum())

Rows removed: 5
Negative prices remaining: 0

In [36]:
print("Zero-price rows:", (df["Price"] == 0).sum())

print("\nZero-price rows with positive quantity:",
      ((df["Price"] == 0) & (df["Quantity"] > 0)).sum())

print("Zero-price rows with negative quantity:",
      ((df["Price"] == 0) & (df["Quantity"] < 0)).sum())

Zero-price rows: 6014

Zero-price rows with positive quantity: 2621
Zero-price rows with negative quantity: 3393

In [37]:
df[df["Price"] == 0]["Description"].value_counts().head(20)

Description
Unknown                          4275
check                             160
?                                  90
damages                            83
damaged                            81
found                              28
missing                            27
sold as set on dotcom              20
Damaged                            17
adjustment                         16
OWL DOORSTOP                       14
POLYESTER FILLER PAD 45x45cm       12
dotcom                             12
POLYESTER FILLER PAD 40x40cm       10
smashed                             9
Found                               9
FRENCH BLUE METAL DOOR SIGN 1       9
thrown away                         9
Unsaleable, destroyed.              9
PICNIC BASKET WICKER LARGE          8
Name: count, dtype: int64

In [38]:
before = len(df)

df = df[df["Price"] > 0].copy()

print("Rows removed:", before - len(df))
print("Zero-price rows remaining:", (df["Price"] == 0).sum())

Rows removed: 6014
Zero-price rows remaining: 0

In [40]:
negative_qty = (df["Quantity"] < 0).sum()

print("Negative quantity rows:", negative_qty)

Negative quantity rows: 19103

In [41]:
negative = df[df["Quantity"] < 0]

print("Negative quantity rows:", len(negative))
print("Cancellation invoices:", negative["Invoice"].astype(str).str.startswith("C").sum())

Negative quantity rows: 19103
Cancellation invoices: 19103

In [42]:
before = len(df)

df = df[df["Quantity"] > 0].copy()

print("Rows removed:", before - len(df))
print("Negative quantities remaining:", (df["Quantity"] < 0).sum())

Rows removed: 19103
Negative quantities remaining: 0

In [43]:
df.isnull().sum()

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
dtype: int64

In [44]:
Q1 = df[["Quantity", "Price"]].quantile(0.25)
Q3 = df[["Quantity", "Price"]].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

print("Lower bounds:")
print(lower)

print("\nUpper bounds:")
print(upper)

Lower bounds:
Quantity   -15.50
Price       -3.07
dtype: float64

Upper bounds:
Quantity    28.50
Price        8.45
dtype: float64

In [45]:
quantity_outliers = (df["Quantity"] > upper["Quantity"]).sum()
price_outliers = (df["Price"] > upper["Price"]).sum()

print("Quantity outliers:", quantity_outliers)
print("Price outliers:", price_outliers)

Quantity outliers: 53061
Price outliers: 79000

In [46]:
print("Highest quantities:")
print(df.nlargest(10, "Quantity")[["Invoice", "StockCode", "Description", "Quantity", "Price"]])

print("\nHighest prices:")
print(df.nlargest(10, "Price")[["Invoice", "StockCode", "Description", "Quantity", "Price"]])

Highest quantities:
        Invoice StockCode                         Description  Quantity  Price
1065882  581483     23843         PAPER CRAFT , LITTLE BIRDIE     80995   2.08
587080   541431     23166      MEDIUM CERAMIC TOP STORAGE JAR     74215   1.04
90857    497946     37410  BLACK AND WHITE PAISLEY FLOWER MUG     19152   0.10
127166   501534     21099         SET/6 STRAWBERRY PAPER CUPS     12960   0.10
127168   501534     21091         SET/6 WOODLAND PAPER PLATES     12960   0.10
127169   501534     21085           SET/6 WOODLAND PAPER CUPS     12744   0.10
127167   501534     21092       SET/6 STRAWBERRY PAPER PLATES     12480   0.10
135027   502269     21984     PACK OF 12 PINK PAISLEY TISSUES     10000   0.25
135028   502269     21982             PACK OF 12 SUKI TISSUES     10000   0.25
135029   502269     21980       PACK OF 12 RED SPOTTY TISSUES     10000   0.25

Highest prices:
        Invoice  StockCode      Description  Quantity     Price
241827   512771          M           Manual         1  25111.09
517955   537632  AMAZONFEE       AMAZON FEE         1  13541.33
825443  A563185          B  Adjust bad debt         1  11062.06
135013   502263          M           Manual         1  10953.50
135015   502265          M           Manual         1  10953.50
342147   522796          M           Manual         1  10468.80
358639   524159          M           Manual         1  10468.80
372834   525399          M           Manual         1  10468.80
74356    496115          M           Manual         1   8985.60
698843   551697       POST          POSTAGE         1   8142.75

In [47]:
special_codes = ["M", "AMAZONFEE", "POST", "B"]

df[df["StockCode"].isin(special_codes)][
    ["Invoice", "StockCode", "Description", "Quantity", "Price"]
].head(20)

      Invoice StockCode Description  Quantity   Price
89     489439      POST     POSTAGE         3   18.00
126    489444      POST     POSTAGE         1  141.00
173    489447      POST     POSTAGE         1  130.00
625    489526      POST     POSTAGE         6   18.00
1244   489557      POST     POSTAGE         4   18.00
2697   489609         M      Manual         1    4.00
6406   489883      POST     POSTAGE         3   18.00
10279  490152      POST     POSTAGE         7   18.00
10344  490158      POST     POSTAGE         3   18.00
11193  490295      POST     POSTAGE         4   28.00
11310  490300         M      Manual         1    0.85
11311  490300         M      Manual         1    0.21
11882  490344      POST     POSTAGE         1   18.00
12475  490395      POST     POSTAGE         2   18.00
12508  490397      POST     POSTAGE         2   15.00
12812  490458      POST     POSTAGE         4   18.00
14596  490564      POST     POSTAGE         7   18.00
15326  490682      POST     POSTAGE         2   18.00
16036  490718      POST     POSTAGE         3   40.00
16184  490733      POST     POSTAGE         3   28.00

In [48]:
df[df["StockCode"].isin(["M", "AMAZONFEE", "POST", "B"])]["StockCode"].value_counts()

StockCode
POST         1851
M             847
AMAZONFEE       3
B               1
Name: count, dtype: int64

In [49]:
before = len(df)

df = df[~df["StockCode"].isin(["M", "AMAZONFEE", "POST", "B"])].copy()

print("Rows removed:", before - len(df))
print("Rows remaining:", len(df))

Rows removed: 2702
Rows remaining: 1005212

In [50]:
Q1 = df["Price"].quantile(0.25)
Q3 = df["Price"].quantile(0.75)
IQR = Q3 - Q1

upper_price = Q3 + 1.5 * IQR

print("Upper price limit:", upper_price)
print("Price outliers remaining:", (df["Price"] > upper_price).sum())

Upper price limit: 8.45
Price outliers remaining: 76869

In [51]:
df.nlargest(20, "Price")[
    ["Invoice", "StockCode", "Description", "Quantity", "Price"]
]

,Invoice,StockCode,Description,Quantity,Price
71077,495798,ADJUST,Adjustment by john on 26/01/2010 17,1,5117.03
823186,562955,DOT,DOTCOM POSTAGE,1,4505.17
1018482,578149,DOT,DOTCOM POSTAGE,1,2275.54
1050353,580610,DOT,DOTCOM POSTAGE,1,2196.67
1050595,580612,DOT,DOTCOM POSTAGE,1,2114.00
1027519,578833,DOT,DOTCOM POSTAGE,1,2028.25
956809,573585,DOT,DOTCOM POSTAGE,1,2019.05
1058952,581023,DOT,DOTCOM POSTAGE,1,1861.46
1067001,581498,DOT,DOTCOM POSTAGE,1,1714.17
1062715,581238,DOT,DOTCOM POSTAGE,1,1683.75
1053544,580727,DOT,DOTCOM POSTAGE,1,1599.26
855089,565847,DOT,DOTCOM POSTAGE,1,1569.04
1034831,579297,DOT,DOTCOM POSTAGE,1,1563.00
996948,576644,DOT,DOTCOM POSTAGE,1,1556.08
1033920,579196,DOT,DOTCOM POSTAGE,1,1526.76
992898,576339,DOT,DOTCOM POSTAGE,1,1500.36
975278,575138,DOT,DOTCOM POSTAGE,1,1483.21
836549,564221,DOT,DOTCOM POSTAGE,1,1325.00
1020188,578270,DOT,DOTCOM POSTAGE,1,1270.06
1009953,577531,DOT,DOTCOM POSTAGE,1,1236.75

In [52]:
special_codes = ["ADJUST", "DOT"]

before = len(df)

df = df[~df["StockCode"].isin(special_codes)].copy()

print("Rows removed:", before - len(df))
print("Rows remaining:", len(df))

Rows removed: 1451
Rows remaining: 1003761

In [53]:
df.nlargest(10, "Price")[
    ["Invoice", "StockCode", "Description", "Quantity", "Price"]
]

,Invoice,StockCode,Description,Quantity,Price
192196,507637,84016,FLAG OF ST GEORGE CAR FLAG,1,1157.15
136403,502451,84016,FLAG OF ST GEORGE CAR FLAG,1,867.79
748132,556444,22502,PICNIC BASKET WICKER 60 PIECES,60,649.50
748143,556446,22502,PICNIC BASKET WICKER 60 PIECES,1,649.50
180997,506571,84016,FLAG OF ST GEORGE CAR FLAG,1,408.40
249673,513566,ADJUST2,Adjustment by Peter on Jun 25 2010,1,358.47
249672,513564,ADJUST2,Adjustment by Peter on Jun 25 2010,1,300.13
268525,515349,22656,VINTAGE BLUE KITCHEN CABINET,1,295.00
268526,515349,22655,VINTAGE RED KITCHEN CABINET,1,295.00
268766,515403,22655,VINTAGE RED KITCHEN CABINET,1,295.00

In [54]:
before = len(df)

df = df[df["StockCode"] != "ADJUST2"].copy()

print("Rows removed:", before - len(df))
print("Rows remaining:", len(df))

Rows removed: 3
Rows remaining: 1003758

In [55]:
df[df["StockCode"] == "ADJUST2"]

Empty DataFrame
Columns: [Invoice, StockCode, Description, Quantity, InvoiceDate, Price, Customer ID, Country]
Index: []

In [56]:
df.isnull().sum()

Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
dtype: int64

In [57]:
print("Final dataset shape:", df.shape)

Final dataset shape: (1003758, 8)

In [58]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [59]:
print("Negative quantities:", (df["Quantity"] < 0).sum())
print("Zero quantities:", (df["Quantity"] == 0).sum())
print("Negative prices:", (df["Price"] < 0).sum())
print("Zero prices:", (df["Price"] == 0).sum())

Negative quantities: 0
Zero quantities: 0
Negative prices: 0
Zero prices: 0

In [60]:
df.to_csv("../data/online_retail_cleaned.csv", index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [61]:
df.to_csv("../data/online_retail_cleaned.csv", index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [62]:
df.to_csv("../data/online_retail_cleaned.csv", index=False)

print("Cleaned dataset saved successfully.")

Cleaned dataset saved successfully.

In [63]:
df.dtypes

Invoice                   str
StockCode                 str
Description               str
Quantity                int64
InvoiceDate    datetime64[us]
Price                 float64
Customer ID            object
Country                   str
dtype: object

In [64]:
df["Year"] = df["InvoiceDate"].dt.year
df["Month"] = df["InvoiceDate"].dt.month
df["Day"] = df["InvoiceDate"].dt.day
df["Hour"] = df["InvoiceDate"].dt.hour
df["DayOfWeek"] = df["InvoiceDate"].dt.dayofweek

df[["InvoiceDate", "Year", "Month", "Day", "Hour", "DayOfWeek"]].head()

          InvoiceDate  Year  Month  Day  Hour  DayOfWeek
0 2009-12-01 07:45:00  2009     12    1     7          1
1 2009-12-01 07:45:00  2009     12    1     7          1
2 2009-12-01 07:45:00  2009     12    1     7          1
3 2009-12-01 07:45:00  2009     12    1     7          1
4 2009-12-01 07:45:00  2009     12    1     7          1

In [65]:
df["TotalAmount"] = df["Quantity"] * df["Price"]

df[["Quantity", "Price", "TotalAmount"]].head()

   Quantity  Price  TotalAmount
0        12   6.95         83.4
1        12   6.75         81.0
2        12   6.75         81.0
3        48   2.10        100.8
4        24   1.25         30.0

In [66]:
print("Final shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())

Final shape: (1003758, 14)

Columns:
['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country', 'Year', 'Month', 'Day', 'Hour', 'DayOfWeek', 'TotalAmount']

In [69]:
df.to_csv("../data/online_retail_preprocessed.csv", index=False)

print("Preprocessed dataset saved successfully.")

Preprocessed dataset saved successfully.

In [70]:
print("Dataset Shape:", df.shape)
print("\nColumns:")
print(df.columns.tolist())
print("\nMissing Values:")
print(df.isnull().sum())

Dataset Shape: (1003758, 14)

Columns:
['Invoice', 'StockCode', 'Description', 'Quantity', 'InvoiceDate', 'Price', 'Customer ID', 'Country', 'Year', 'Month', 'Day', 'Hour', 'DayOfWeek', 'TotalAmount']

Missing Values:
Invoice        0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
Price          0
Customer ID    0
Country        0
Year           0
Month          0
Day            0
Hour           0
DayOfWeek      0
TotalAmount    0
dtype: int64

In [71]:
print("Duplicate rows:", df.duplicated().sum())
print("Negative quantities:", (df["Quantity"] < 0).sum())
print("Zero quantities:", (df["Quantity"] == 0).sum())
print("Negative prices:", (df["Price"] < 0).sum())
print("Zero prices:", (df["Price"] == 0).sum())

Duplicate rows: 0
Negative quantities: 0
Zero quantities: 0
Negative prices: 0
Zero prices: 0

In [72]:
df[[
    "InvoiceDate",
    "Year",
    "Month",
    "Day",
    "Hour",
    "DayOfWeek",
    "Quantity",
    "Price",
    "TotalAmount"
]].head(10)

,InvoiceDate,Year,Month,Day,Hour,DayOfWeek,Quantity,Price,TotalAmount
0,2009-12-01 07:45:00,2009,12,1,7,1,12,6.95,83.4
1,2009-12-01 07:45:00,2009,12,1,7,1,12,6.75,81.0
2,2009-12-01 07:45:00,2009,12,1,7,1,12,6.75,81.0
3,2009-12-01 07:45:00,2009,12,1,7,1,48,2.10,100.8
4,2009-12-01 07:45:00,2009,12,1,7,1,24,1.25,30.0
5,2009-12-01 07:45:00,2009,12,1,7,1,24,1.65,39.6
6,2009-12-01 07:45:00,2009,12,1,7,1,24,1.25,30.0
7,2009-12-01 07:45:00,2009,12,1,7,1,10,5.95,59.5
8,2009-12-01 07:46:00,2009,12,1,7,1,12,2.55,30.6
9,2009-12-01 07:46:00,2009,12,1,7,1,12,3.75,45.0

In [73]:
import os

file_path = "../data/online_retail_preprocessed.csv"

print("File exists:", os.path.exists(file_path))
print("File size (MB):", round(os.path.getsize(file_path) / (1024 * 1024), 2))

File exists: True
File size (MB): 108.83

In [74]:
print("FINAL DATASET SUMMARY")
print("---------------------")
print("Rows:", len(df))
print("Columns:", len(df.columns))
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())
print("Negative quantities:", (df["Quantity"] < 0).sum())
print("Zero quantities:", (df["Quantity"] == 0).sum())
print("Negative prices:", (df["Price"] < 0).sum())
print("Zero prices:", (df["Price"] == 0).sum())
print("Date range:", df["InvoiceDate"].min(), "to", df["InvoiceDate"].max())

FINAL DATASET SUMMARY
---------------------
Rows: 1003758
Columns: 14
Missing values: 0
Duplicate rows: 0
Negative quantities: 0
Zero quantities: 0
Negative prices: 0
Zero prices: 0
Date range: 2009-12-01 07:45:00 to 2011-12-09 12:50:00